// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaymentOrderOps.Infrastructure.Persistence;

#nullable disable

namespace PaymentOrderOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829235243_AddServiceEnvironment")]
    partial class AddServiceEnvironment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaymentOrderOps.Domain.ServiceHealth.ServiceHealthCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Dev");

                    b.Property<int>("ExpectedStatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(200);

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Headers");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Environment", "Group")
                        .HasDatabaseName("IX_ServiceHealthChecks_Environment_Group");

                    b.HasIndex("Environment", "Method", "NormalizedUrl")
                        .IsUnique()
                        .HasDatabaseName("IX_ServiceHealthChecks_Environment_Method_NormalizedUrl")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("ServiceHealthChecks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f1a1-0001-7000-8000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Dev",
                            ExpectedStatusCode = 200,
                            Group = "Payment",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Payment Gateway",
                            NormalizedUrl = "https://payment-gateway.boyner.internal/actuator/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://payment-gateway.boyner.internal/actuator/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0001-7000-8000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Dev",
                            ExpectedStatusCode = 200,
                            Group = "Payment",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "3DS Service",
                            NormalizedUrl = "https://payment-3ds.boyner.internal/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://payment-3ds.boyner.internal/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0001-7000-8000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Dev",
                            ExpectedStatusCode = 200,
                            Group = "Payment",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Wallet Service",
                            NormalizedUrl = "https://wallet.boyner.internal/actuator/health/liveness",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://wallet.boyner.internal/actuator/health/liveness"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0001-7000-8000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Dev",
                            ExpectedStatusCode = 200,
                            Group = "Order",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Order Orchestrator",
                            NormalizedUrl = "https://order-orchestrator.boyner.internal/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://order-orchestrator.boyner.internal/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0001-7000-8000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Dev",
                            ExpectedStatusCode = 200,
                            Group = "Order",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Fulfillment Service",
                            NormalizedUrl = "https://fulfillment.boyner.internal/actuator/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://fulfillment.boyner.internal/actuator/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0001-7000-8000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Dev",
                            ExpectedStatusCode = 200,
                            Group = "Platform",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Notification Service",
                            NormalizedUrl = "https://notification.boyner.internal/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://notification.boyner.internal/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0002-7000-8000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Preprod",
                            ExpectedStatusCode = 200,
                            Group = "Payment",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Payment Gateway",
                            NormalizedUrl = "https://payment-gateway.boyner.internal/actuator/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://payment-gateway.boyner.internal/actuator/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0002-7000-8000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Preprod",
                            ExpectedStatusCode = 200,
                            Group = "Payment",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "3DS Service",
                            NormalizedUrl = "https://payment-3ds.boyner.internal/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://payment-3ds.boyner.internal/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0002-7000-8000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Preprod",
                            ExpectedStatusCode = 200,
                            Group = "Payment",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Wallet Service",
                            NormalizedUrl = "https://wallet.boyner.internal/actuator/health/liveness",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://wallet.boyner.internal/actuator/health/liveness"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0002-7000-8000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Preprod",
                            ExpectedStatusCode = 200,
                            Group = "Order",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Order Orchestrator",
                            NormalizedUrl = "https://order-orchestrator.boyner.internal/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://order-orchestrator.boyner.internal/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0002-7000-8000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Preprod",
                            ExpectedStatusCode = 200,
                            Group = "Order",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Fulfillment Service",
                            NormalizedUrl = "https://fulfillment.boyner.internal/actuator/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://fulfillment.boyner.internal/actuator/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0002-7000-8000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Preprod",
                            ExpectedStatusCode = 200,
                            Group = "Platform",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Notification Service",
                            NormalizedUrl = "https://notification.boyner.internal/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://notification.boyner.internal/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0003-7000-8000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Production",
                            ExpectedStatusCode = 200,
                            Group = "Payment",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Payment Gateway",
                            NormalizedUrl = "https://payment-gateway.boyner.internal/actuator/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://payment-gateway.boyner.internal/actuator/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0003-7000-8000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Production",
                            ExpectedStatusCode = 200,
                            Group = "Payment",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "3DS Service",
                            NormalizedUrl = "https://payment-3ds.boyner.internal/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://payment-3ds.boyner.internal/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0003-7000-8000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Production",
                            ExpectedStatusCode = 200,
                            Group = "Payment",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Wallet Service",
                            NormalizedUrl = "https://wallet.boyner.internal/actuator/health/liveness",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://wallet.boyner.internal/actuator/health/liveness"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0003-7000-8000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Production",
                            ExpectedStatusCode = 200,
                            Group = "Order",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Order Orchestrator",
                            NormalizedUrl = "https://order-orchestrator.boyner.internal/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://order-orchestrator.boyner.internal/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0003-7000-8000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Production",
                            ExpectedStatusCode = 200,
                            Group = "Order",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Fulfillment Service",
                            NormalizedUrl = "https://fulfillment.boyner.internal/actuator/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://fulfillment.boyner.internal/actuator/health"
                        },
                        new
                        {
                            Id = new Guid("0198f1a1-0003-7000-8000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Environment = "Production",
                            ExpectedStatusCode = 200,
                            Group = "Platform",
                            Headers = "{}",
                            IsDeleted = false,
                            IsEnabled = true,
                            Method = "Get",
                            Name = "Notification Service",
                            NormalizedUrl = "https://notification.boyner.internal/health",
                            Source = "Builtin",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://notification.boyner.internal/health"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
