<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PaymentOrderOps.Api.Tests</RootNamespace>
    <AssemblyName>PaymentOrderOps.Api.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PaymentOrderOps.Api\PaymentOrderOps.Api.csproj" />
    <ProjectReference Include="..\..\src\PaymentOrderOps.Infrastructure\PaymentOrderOps.Infrastructure.csproj" />
  </ItemGroup>

</Project>
